### ISSUE TITLE
Flag to specify ffmpeg location?

### ISSUE THREAD

**Issue by chrisvire** [gordon-cs/appbuilder-storybuilder#113]
We talked early on about being able to specify the location of FFmpeg.  Scripture App Builder include FFmpeg as a binary in its packaging and it isn't on the path.  Is this still possible to provide a flag to specify the ffmpeg location?

**Comment by Davideo37** [comment]
I'm not sure why I wasn't notified of this issue when it was posted. I can try and get this working by today.

**Comment by Davideo37** [comment]
Issue resolved
