### ISSUE TITLE
Build binaries that are targeted at platforms

### ISSUE THREAD

**Issue by chrisvire** [gordon-cs/appbuilder-storybuilder#45]
I believer you are running the script by using go as an interpreter based on the current directory.  For deployment in SAB, we will need to compile to GO code to a platform-specific binary.

I asked colleagues who release go applications.  They said to use https://github.com/goplus/gox.

Something like:
```
targets=( "darwin/amd64" "linux/386" "linux/amd64" "linux/arm" "windows/386" )
distPath="../../dist"

for target in "${targets[@]}"
do
    # Build binary using gox
    gox -osarch="${target}" -output="${distPath}/${target}/my-project"
...
```

**Comment by Davideo37** [comment]
Resolved
